### ISSUE TITLE
Configuration for cycling (wrapping?)

### ISSUE THREAD

**Issue by AlexWayfer** [sunwxg/gnome-shell-extension-panelScroll#4]
Hello.

I see your extension switch desktops infinitely, so if I'm on the last one — switching further returns me to the first one and vice-versa.

But this is not GNOME default behavior. And some other extensions, like [Top Panel Workspace Scroll](https://extensions.gnome.org/extension/701/top-panel-workspace-scroll/), don't have such cycling.

But I appreciate configuration and current default behavior, which can be more suitable for some users, so I suggest to just add an option to configuration for this.

**Comment by sunwxg** [comment]
Okay.

**Comment by ejemba** [comment]
Hi @sunwxg , 
like @AlexWayfer I'd like to have an option to prevent cycling.
Do you think you can work on this ?

Thank you

**Comment by FelixFourcolor** [comment]
For those who wants a quick hack to disable wraparound, changes these two lines in `extension.js`:

![Screenshot from 2023-10-22 01-43-55](https://github.com/sunwxg/gnome-shell-extension-panelScroll/assets/34260584/3127ab05-79d7-462a-9d98-5605aced4e34)

Since I like Gnome's default behavior, I will run this until the proper update arrives.

**Comment by FelixFourcolor** [comment]
@sunwxg Thank you!
